# Generated by Django 3.0.1 on 2019-12-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание Задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание Задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('0', 'низкий'), ('1', 'средний'), ('2', 'высокий')], default='0', max_length=5, null=True, verbose_name='приоритет'),
        ),
    ]
